# Generated by Django 4.2 on 2023-04-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellido',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombre',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='apellido',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
